# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 02:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vid',
            new_name='Video',
        ),
    ]
