# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20170125_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='flash_video',
            field=models.FileField(default=django.utils.timezone.now, upload_to=b'', verbose_name='flash_video'),
            preserve_default=False,
        ),
    ]
