# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_flash_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default='Community Video   ', max_length=100),
        ),
    ]
