# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_rating_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='video.Video'),
        ),
    ]
