# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_auto_20170216_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rate_comment',
            field=models.CharField(default='No Comment', max_length=200),
        ),
    ]
