# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_auto_20170216_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='video.Video'),
        ),
    ]
